from typing import TypedDict, AsyncIterator

class ObjectMetadata(TypedDict):
    location: str
    last_modified: str
    size_bytes: int
    content_type: str | None
    e_tag: str | None
    version: str | None

class ByteStream(AsyncIterator[bytes]):
    """Async byte-stream returned by :py:meth:`ObjectStorageClient.get_object_stream`."""
    def __aiter__(self) -> AsyncIterator[bytes]: ...
    async def __anext__(self) -> bytes: ...
    async def next(self) -> bytes: ...

class ObjectStorageClient:
    def __init__(self) -> None: ...
    async def get_object(self, url: str) -> bytes: ...
    async def get_object_stream(self, url: str) -> ByteStream: ...
    async def put_object(self, url: str, data: bytes | list[int]) -> None: ...
    async def delete_object(self, url: str) -> None: ...
    async def list_objects(self, url: str) -> list[str]: ...
    async def get_object_metadata(self, url: str) -> ObjectMetadata: ...
    async def object_exists(self, url: str) -> bool: ...
    async def create_bucket(self, url: str) -> None: ...
    async def bucket_exists(self, url: str) -> bool: ...
    async def copy_object(self, from_url: str, to_url: str) -> None: ...
    async def move_object(self, from_url: str, to_url: str) -> None: ...
    async def get_pre_signed_url(
        self,
        url: str,
        method: str = "GET",
        expires_in_secs: int = 3600,
        content_length: int | None = None,
        content_type: str | None = None,
    ) -> str: ...
    async def get_pre_signed_urls(
        self,
        urls: list[str],
        method: str = "GET",
        expires_in_secs: int = 3600,
        content_length: int | None = None,
        content_type: str | None = None,
    ) -> list[str]: ...
