from typing import Any, TypedDict, AsyncIterator

class ObjectMeta(TypedDict):
    location: str
    last_modified: str
    size: int
    e_tag: str | None
    version: str | None

class ObjectStorageClient:
    def __init__(self) -> None: ...
    async def get_object(self, url: str) -> bytes: ...
    def get_object_stream(self, url: str) -> AsyncIterator[bytes]: ...
    async def put_object(self, url: str, data: bytes) -> None: ...
    async def delete_object(self, url: str) -> None: ...
    async def list_objects(self, url: str) -> list[str]: ...
    async def head(self, url: str) -> ObjectMeta: ...
    async def copy_object(self, from_url: str, to_url: str) -> None: ...
    async def move_object(self, from_url: str, to_url: str) -> None: ...
    async def get_pre_signed_url(
        self,
        url: str,
        method: str = "GET",
        expires_in_secs: int = 3600,
        content_length: int | None = None,
        content_type: str | None = None,
    ) -> str: ...
    async def get_pre_signed_urls(
        self,
        urls: list[str],
        method: str = "GET",
        expires_in_secs: int = 3600,
        content_length: int | None = None,
        content_type: str | None = None,
    ) -> list[str]: ...
