from typing import Any, TypedDict, List

class ObjectMeta(TypedDict):
    location: str
    last_modified: str
    size: int
    e_tag: str | None
    version: str | None

class ObjectStorageClient:
    def __init__(self) -> None: ...
    async def get(self, url: str) -> bytes: ...
    async def put(self, url: str, data: bytes) -> None: ...
    async def delete(self, url: str) -> None: ...
    async def list(self, url: str) -> List[str]: ...
    async def head(self, url: str) -> ObjectMeta: ...
    async def copy(self, from_url: str, to_url: str) -> None: ...
    async def move_object(self, from_url: str, to_url: str) -> None: ...
